### ISSUE TITLE
ERRORS on make

### ISSUE THREAD

**Issue by GeezerGamer** [skitzo2000/GMMK2-65#1]
I get these errors when trying to compile firmware.
Ψ Compiling keymap with make --jobs=1 gmmk/gmmk2/p65/ansi:skitzo

QMK Firmware 0.15.25
Making gmmk/gmmk2/p65/ansi with keymap skitzo

arm-none-eabi-gcc.exe (GCC) 10.1.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/gmmk/gmmk2/src/eeprom_flash.c
    [OK]
Compiling: keyboards/gmmk/gmmk2/src/flash_spi.c
    [OK]
Compiling: keyboards/gmmk/gmmk2/src/wb32_spi_master.c
    [OK]
Compiling: keyboards/gmmk/gmmk2/gmmk2.c
    [OK]
Compiling: keyboards/gmmk/gmmk2/p65/ansi/ansi.c
    [OK]
Compiling: keyboards/gmmk/gmmk2/p65/ansi/keymaps/skitzo/keymap.c
   keyboards/gmmk/gmmk2/p65/ansi/keymaps/skitzo/keymap.c: In function 'layer_state_set_user':
keyboards/gmmk/gmmk2/p65/ansi/keymaps/skitzo/keymap.c:138:34: error: 'RGB_MATRIX_SOLID_REACTIVE' undeclared (first use in this function); did you mean 'RGB_MATRIX_SOLID_COLOR'?
  138 |         rgb_matrix_mode_noeeprom(RGB_MATRIX_SOLID_REACTIVE);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  RGB_MATRIX_SOLID_COLOR
keyboards/gmmk/gmmk2/p65/ansi/keymaps/skitzo/keymap.c:138:34: note: each undeclared identifier is reported only once for each function it appears in
keyboards/gmmk/gmmk2/p65/ansi/keymaps/skitzo/keymap.c:141:34: error: 'RGB_MATRIX_TYPING_HEATMAP' undeclared (first use in this function); did you mean 'ENABLE_RGB_MATRIX_TYPING_HEATMAP'?
  141 |         rgb_matrix_mode_noeeprom(RGB_MATRIX_TYPING_HEATMAP);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  ENABLE_RGB_MATRIX_TYPING_HEATMAP
keyboards/gmmk/gmmk2/p65/ansi/keymaps/skitzo/keymap.c:146:34: error: 'RGB_MATRIX_SOLID_MULTISPLASH' undeclared (first use in this function); did you mean 'ENABLE_RGB_MATRIX_SOLID_MULTISPLASH'?

  146 |         rgb_matrix_mode_noeeprom(RGB_MATRIX_SOLID_MULTISPLASH);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                  ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
 [ERRORS]
 |
 |
 |
make[1]: *** [builddefs/common_rules.mk:456: .build/obj_gmmk_gmmk2_p65_ansi_skitzo/keyboards/gmmk/gmmk2/p65/ansi/keymaps/skitzo/keymap.o] Error 1
Make finished with errors
make: *** [Makefile:413: gmmk/gmmk2/p65/ansi:skitzo] Error 1

**Comment by skitzo2000** [comment]
What are compiling with?  QMK_msys, WSL, etc
What command are you using to compile with?  For reference this is my compile command

`qmk compile -kb gmmk/gmmk2/p65/ansi -km skitzo2000`

**Comment by GeezerGamer** [comment]
I'm compiling with QMK_msys. The command is
qmk compile -kb gmmk/gmmk2/p65/ansi -km skitzo

**Comment by skitzo2000** [comment]
I found the issue!  I just pushed a commit to add a few statements to the config.c that should fix everything up.  LMK how it goes.

**Comment by GeezerGamer** [comment]
Compiled fine with the fix. Thanks for your hard work.
